name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up PHP
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: mysqli

    # Install dependencies
    - name: Install dependencies
      run: |
        composer install

    # Run PHPUnit tests
    - name: Run PHPUnit tests
      run: |
        vendor/bin/phpunit tests --colors=always

    # Optional: Run Selenium tests for report.php
    - name: Run Selenium tests
      if: success() # Only run if previous steps succeeded
      uses: GabrielBB/xvfb-action@v1
      with:
        run: |
          python3 -m pip install selenium
          python3 tests/e2e_test.py
