name: CI Pipeline

on:
  push:
    branches:
      - main   # Run the workflow when code is pushed to the main branch
  pull_request:
    branches:
      - main   # Run the workflow on pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      # Step 1: Check out the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'  # Specify the PHP version
          extensions: mbstring, mysqli  # Include PHP extensions
          ini-values: post_max_size=256M, upload_max_filesize=256M

      # Step 3: Install dependencies using Composer
      - name: Install Dependencies
        run: composer install

      # Step 4: Run the tests
      - name: Run Tests
        run: |
          vendor/bin/phpunit tests/  # Update the path to your test directory
